### ISSUE TITLE
Script Error "http://maps.google.com/maps-api-v3/api/js/23/7/intl/fr_ALL/onion.js"

### ISSUE THREAD

**Issue by JPL-BELG** [RRUZ/blog#2]
Hi Rodrigo,

Since december, I have the following  script error
"URL: http://maps.google.com/maps-api-v3/api/js/23/7/intl/fr_ALL/onion.js"
I see on the internet that other softwares meet the same problem (see for example http://faq.pcsoft.fr/12194-faq-read.awp, in french.  It is exactly the same error...).
The Company says that this error message could be due to the fact that Google forbids some request depending on its "origin" (I don't know what it means...)
They explain that (in french) "il faut donc configurer l'ActiveX de Internet Explorer pour que les requêtes envoyées soient identifiées comme provenant de Internet Explorer 11"  
In English: The Internet Explorer ActiveX must be configured in a way that the sent requests are identified as if they are sent from Internet Explorer 11"
I use the TWebBrowser component in Delphi XE7.
Do you have an idea?
Thank you.

**Comment by JPL-BELG** [comment]
Hi Rodrigo,
"http://maps.google.com/maps/api/js?v=3.22&sensor=false" works..
So v=3.22 seems to solve this problem.
How to know which version must be coded?

Closing the StreetView window is stil a problem (the close little button does'nt appear.  The mode must be programmatically closed).

**Comment by RRUZ** [comment]
Check this article https://theroadtodelphi.wordpress.com/2015/10/19/important-note-about-using-the-google-maps-api-from-desktop-apps/
